apiVersion: apps/v1
kind: Deployment
metadata:
  name: bingo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bingo
  template:
    metadata:
      labels:
        app: bingo
    spec:
      containers:
        - name: bingo-container
          image: your-dockerhub-username/bingo-app:latest
          ports:
            - containerPort: 3000
